### ISSUE TITLE
SyntaxError: invalid syntax,

### ISSUE THREAD

**Issue by shrikant4learning** [gradam/django-better-admin-arrayfield#9]
* Django better admin ArrayField version: 1.0.2 release
* Django version: 1.11.17
* Python version: 2.7
* Operating System: Windows 10

### Description
Below are the steps I took till now:
1. pip install django-better-admin-arrayfield
2. included **'django_better_admin_arrayfield.apps.DjangoBetterAdminArrayfieldConfig',** as the last field under 'installed apps' in settings
3. replaced old arrayfield import in models.py with '**from django_better_admin_arrayfield.models.fields import ArrayField'**
4. In admin.py, imported DynamicArrayMixin as below:
   from django_better_admin_arrayfield.admin.mixins import DynamicArrayMixin
5. Created ModelAdmin in admin.py as:
   class SpotModelAdmin(admin.ModelAdmin, DynamicArrayMixin):
       pass
6. Registered model with its ModelAdmin as below:
     admin.site.register(Spot, SpotModelAdmin) _#(Spot is the name of model in which arrayfield is used.)_
7. When running makemigrations, I am getting syntax error.
    Check following traceback after running command makemigrations.
```
>> python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Program Files (x86)\Python\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "D:\Program Files (x86)\Python\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "D:\Program Files (x86)\Python\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Program Files (x86)\Python\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models()
  File "D:\Program Files (x86)\Python\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\Program Files (x86)\Python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\SHRIKANT\django practice\myproject\travelsite\mockup3\spot\models.py", line 5, in <module>
    from django_better_admin_arrayfield.models.fields import ArrayField
  File "D:\Program Files (x86)\Python\lib\site-packages\django_better_admin_arrayfield\models\fields.py", line 8
    return super().formfield(**{"form_class": DynamicArrayField, **kwargs})
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by gradam** [comment]
@shrikant4learning This package does not support python2. That's why you are getting the Syntax Error.
